// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-LWGIsruY5g32XhAmLmzw3Vzc77hB1oc',
    appId: '1:840349971179:web:1aacf3e9284394e79e44ae',
    messagingSenderId: '840349971179',
    projectId: 'ai-mobile-b9ce9',
    authDomain: 'ai-mobile-b9ce9.firebaseapp.com',
    storageBucket: 'ai-mobile-b9ce9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3julQS2j_0-wpIam1t5WVDIGfn5omac8',
    appId: '1:840349971179:android:40a86ae40f1fdf1c9e44ae',
    messagingSenderId: '840349971179',
    projectId: 'ai-mobile-b9ce9',
    storageBucket: 'ai-mobile-b9ce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5sswoa7ROREM7iKqFen8V68Ane700AY',
    appId: '1:840349971179:ios:a3bae57d581c68889e44ae',
    messagingSenderId: '840349971179',
    projectId: 'ai-mobile-b9ce9',
    storageBucket: 'ai-mobile-b9ce9.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF5sswoa7ROREM7iKqFen8V68Ane700AY',
    appId: '1:840349971179:ios:a3bae57d581c68889e44ae',
    messagingSenderId: '840349971179',
    projectId: 'ai-mobile-b9ce9',
    storageBucket: 'ai-mobile-b9ce9.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-LWGIsruY5g32XhAmLmzw3Vzc77hB1oc',
    appId: '1:840349971179:web:086dfeb2055b3ea69e44ae',
    messagingSenderId: '840349971179',
    projectId: 'ai-mobile-b9ce9',
    authDomain: 'ai-mobile-b9ce9.firebaseapp.com',
    storageBucket: 'ai-mobile-b9ce9.firebasestorage.app',
  );
}
